# 情報工学工房 第二回レポート課題

## 課題
1. 活性化関数であるSigmoid関数とSoftmax関数をpythonで実装する。Sigmoid関数は次の課題でそのまま使用するので、Numpyを入力とする。
2. 3層マルチパーセプトロンによるNNの実装を行い、出力が正しいか確認する。下記のサンプルコードにおけるforward部分を実装する。活性化関数にはSigmoid関数を使用する。
3. バッチ処理の行い方についてサンプルコードを実行し、扱い方のイメージを掴む。複数の入力を逐次的に処理する。

## 回答
実装したSigmoid関数とSoftmax関数、および3層マルチパーセプトロンによるNNは次の通り。

In [16]:
import numpy as np
import random

def sigmoid(x):
    return 1 / (1 + np.exp(-x))
    
def softmax(a):
    exp_a = np.exp(a)
    y = exp_a / np.sum(exp_a)
    return y

def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([[0.1, 0.2, 0.3]])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([[0.1, 0.2]])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([[0.1, 0.2]])
    return network

def forward(network, x):
    # layer 1
    W1 = network['W1']
    b1 = network['b1']
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    # layer2
    W2 = network['W2']
    b2 = network['b2']
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    # layer 3
    W3 = network['W3']
    b3 = network['b3']
    y = np.dot(z2, W3) + b3
    return y

network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)   # Expected [0.31682708 0.69627909]

batch_size = 16
x = np.random.rand(1000, 2)
for i in range(0, len(x), batch_size):
    x_batch = x[i : i + batch_size]
    y_batch = forward(network, x_batch)
    print(y_batch)

[[0.31682708 0.69627909]]
[[0.31303197 0.68784878]
 [0.31388041 0.68972226]
 [0.31881528 0.70069718]
 [0.31611981 0.69470326]
 [0.3149527  0.69211345]
 [0.31498259 0.69217206]
 [0.31601772 0.69447549]
 [0.31557904 0.69350556]
 [0.31055613 0.68235302]
 [0.31347801 0.68883783]
 [0.31224224 0.68608667]
 [0.31441567 0.69090596]
 [0.31532084 0.69292226]
 [0.31223779 0.68608332]
 [0.31605667 0.69456565]
 [0.30931317 0.67959633]]
[[0.31431798 0.69069742]
 [0.3090644  0.67904574]
 [0.31697553 0.69660569]
 [0.3104764  0.68217668]
 [0.31149774 0.68444261]
 [0.31589389 0.69418818]
 [0.3130012  0.68777015]
 [0.31024694 0.6816609 ]
 [0.3167916  0.69619392]
 [0.31650615 0.6955625 ]
 [0.31353797 0.68895605]
 [0.31209264 0.68576265]
 [0.31244206 0.68653207]
 [0.31379162 0.68951777]
 [0.31390254 0.6897806 ]
 [0.31503626 0.69229101]]
[[0.31640951 0.69534638]
 [0.3125841  0.68685187]
 [0.31194125 0.68542751]
 [0.31597908 0.69438343]
 [0.31129126 0.68397945]
 [0.31200573 0.6855607 ]
 [0.3139904  0.6899802

以上の結果から、NumPy配列を入力としたSigmoid関数、Softmax関数及びNNの実装とそのパッチ処理ができたといえる。

## 感想
- ニューラルネットワークが数学的に表現できるということが実感できた
- initの値を調整すると

## 参考
- http://pr.cei.uec.ac.jp/kobo2020/index.php?Pytorch%E3%81%AB%E3%82%88%E3%82%8B%E6%B7%B1%E5%B1%A4%E5%AD%A6%E7%BF%92%20%E7%94%BB%E5%83%8F%E8%AA%8D%E8%AD%98%E3%83%BB%E7%94%9F%E6%88%90
- http://yusuke-ujitoko.hatenablog.com/entry/2016/12/25/232555